# Generated by Django 4.0.6 on 2022-08-16 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_launch', models.DateTimeField()),
                ('delivered_message', models.TextField(max_length=500)),
                ('mobile_code', models.CharField(max_length=4)),
                ('scheduled_message', models.DateTimeField()),
            ],
            options={
                'db_table': 'рассылка',
            },
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_client', models.CharField(max_length=11)),
                ('mobile_code', models.CharField(max_length=4)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'клиент',
            },
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_making', models.DateTimeField()),
                ('status', models.CharField(choices=[{'не отправлено': 'не отправлено', 'отправлено': 'отправлено'}], max_length=13)),
                ('sent_message_id', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='сервис.client')),
            ],
            options={
                'db_table': 'сообщение',
            },
        ),
    ]
