# Generated by Django 4.0.6 on 2022-08-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('сервис', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='client',
            new_name='client_s',
        ),
    ]
