# Generated by Django 4.0.6 on 2022-08-16 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('сервис', '0002_rename_client_client_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_message_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='сервис.broadcast'),
        ),
    ]
